spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_online_management_system?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimeZone=GTM+8
    username: root
    password: 5201314
  thymeleaf:
    cache: false
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
mybatis:
  mapper-locations: com/fc/mapper/*.xml
  type-aliases-package: com.fc.entity
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
